title: Your Name
description: Personal CV and portfolio
# Use the Hyde theme via GitHub remote_theme

# For local builds only (see "Develop locally" section)
plugins:
  - jekyll-remote-theme

remote_theme: poole/hyde


# Optional: set permalink style
permalink: /:title/

# Site URL (recommended once your site is live)
# url: https://YOURUSERNAME.github.io
# baseurl: ""  # leave empty for personal site; set to "/repo-name" for project site