title: Your Name
description: Personal CV and portfolio
# Use the Hyde theme via GitHub remote_theme

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Optional: set permalink style
#permalink: /:title/

# Site URL (recommended once your site is live)
# url: https://YOURUSERNAME.github.io
# baseurl: ""  # leave empty for personal site; set to "/repo-name" for project site